puts "Johnny".object_id
puts "Johnny".object_id
puts "Johnny".object_id
puts "Johnny".object_id
puts "Johnny".object_id
puts "------------------------"
puts :Johnny.object_id
puts :Johnny.object_id
puts :Johnny.object_id
puts :Johnny.object_id
puts :Johnny.object_id
puts :Johnny.object_id